import type { Venue } from "./types";

export const VENUES: Venue[] = [
  {
    id: "pineapples",
    name: "Pineapples",
    city: "Eau Gallie",
    neighborhood: "EGAD",
    address: "1434 Pineapple Ave, Melbourne, FL 32935",
    lat: 28.1325,
    lng: -80.6309,
    url: "https://pineapplesegad.com",
  },
  {
    id: "king-center",
    name: "King Center for the Performing Arts",
    city: "Melbourne",
    address: "3865 N Wickham Rd, Melbourne, FL 32935",
    lat: 28.1619,
    lng: -80.7015,
    url: "https://www.kingcenter.com",
  },
  {
    id: "squid-lips-egad",
    name: "Squid Lips",
    city: "Eau Gallie",
    neighborhood: "EGAD",
    address: "1477 Pineapple Ave, Melbourne, FL 32935",
    lat: 28.1334,
    lng: -80.6315,
    url: "https://www.squidlipsgrill.com",
  },
  {
    id: "squid-lips-seb",
    name: "Squid Lips",
    city: "Sebastian",
    address: "1660 N Indian River Dr, Sebastian, FL 32958",
    lat: 27.832,
    lng: -80.474,
    url: "https://www.squidlipsgrill.com",
  },
  {
    id: "squid-lips-cb",
    name: "Squid Lips",
    city: "Cocoa Beach",
    address: "2200 S Orlando Ave, Cocoa Beach, FL 32931",
    lat: 28.3105,
    lng: -80.6085,
    url: "https://www.squidlipsgrill.com",
  },
  {
    id: "earls",
    name: "Earl's Hideaway Lounge",
    city: "Sebastian",
    address: "1585 Indian River Dr, Sebastian, FL 32958",
    lat: 27.8169,
    lng: -80.4705,
  },
  {
    id: "lous-blues",
    name: "Lou's Blues Bar & Grill",
    city: "Indialantic",
    address: "1 Wave Crest Ave, Indialantic, FL 32903",
    lat: 28.0894,
    lng: -80.5668,
  },
  {
    id: "heidis",
    name: "Heidi's Jazz Club",
    city: "Cocoa Beach",
    address: "7 N Orlando Ave, Cocoa Beach, FL 32931",
    lat: 28.3178,
    lng: -80.611,
    url: "https://heidisjazzclub.com",
  },
  {
    id: "foo-bar",
    name: "Foo Bar",
    city: "Cocoa Beach",
    address: "6 N Orlando Ave, Cocoa Beach, FL 32931",
    lat: 28.318,
    lng: -80.6108,
  },
  {
    id: "dirty-birds",
    name: "Dirty Birds",
    city: "Cocoa Beach",
    address: "401 W Cocoa Beach Causeway, Cocoa Beach, FL 32931",
    lat: 28.3562,
    lng: -80.6124,
  },
  {
    id: "sanbar-sat",
    name: "Sanbar",
    city: "Satellite Beach",
    address: "1850 Highway A1A, Satellite Beach, FL 32937",
    lat: 28.1762,
    lng: -80.5904,
  },
  {
    id: "sanbar-cb",
    name: "Sanbar",
    city: "Cocoa Beach",
    address: "3700 N Atlantic Ave, Cocoa Beach, FL 32931",
    lat: 28.3555,
    lng: -80.6082,
  },
  {
    id: "cadillac-cove",
    name: "Cadillac Cove",
    city: "Indian Harbour Beach",
    address: "1420 S Patrick Dr, Indian Harbour Beach, FL 32937",
    lat: 28.1488,
    lng: -80.5885,
  },
  {
    id: "tide-tonic",
    name: "Tide & Tonic",
    city: "Cocoa Beach",
    address: "1 N Atlantic Ave, Cocoa Beach, FL 32931",
    lat: 28.3202,
    lng: -80.6076,
  },
  {
    id: "summer-crush",
    name: "Summer Crush Vineyard & Winery",
    city: "Fort Pierce",
    address: "3350 SW St Lucie Blvd, Fort Pierce, FL 34953",
    lat: 27.4284,
    lng: -80.3852,
    url: "https://www.summercrushwine.com",
  },
  {
    id: "hell-n-blazes",
    name: "Hell 'n Blazes Brewing Company",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "530 E New Haven Ave, Melbourne, FL 32901",
    lat: 28.0832,
    lng: -80.6055,
    url: "https://hellnblazesbrewing.com",
  },
  {
    id: "debauchery",
    name: "Debauchery",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "900 E New Haven Ave, Melbourne, FL 32901",
    lat: 28.0835,
    lng: -80.601,
  },
  {
    id: "creek-saloon",
    name: "The Creek Saloon",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "829 E New Haven Ave, Melbourne, FL 32901",
    lat: 28.0834,
    lng: -80.6025,
  },
  {
    id: "melbourne-auditorium",
    name: "Melbourne Auditorium",
    city: "Melbourne",
    address: "625 E Hibiscus Blvd, Melbourne, FL 32901",
    lat: 28.0795,
    lng: -80.6088,
  },
  {
    id: "riverview-park",
    name: "Riverview Park",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "2400 Riverview Dr, Melbourne, FL 32901",
    lat: 28.077,
    lng: -80.601,
    url: "https://downtownmelbourne.com",
  },
  {
    id: "wickham-park",
    name: "Wickham Park",
    city: "Melbourne",
    address: "2500 Parkway Dr, Melbourne, FL 32935",
    lat: 28.1555,
    lng: -80.655,
  },
  {
    id: "humiston",
    name: "Humiston Park",
    city: "Vero Beach",
    neighborhood: "Ocean Drive",
    address: "3000 Ocean Dr, Vero Beach, FL 32963",
    lat: 27.6395,
    lng: -80.3578,
  },
  {
    id: "marina-square",
    name: "Marina Square",
    city: "Fort Pierce",
    neighborhood: "Downtown",
    address: "101 Melody Ln, Fort Pierce, FL 34950",
    lat: 27.4475,
    lng: -80.3245,
    url: "https://www.fortpiercefarmersmarket.com",
  },
  {
    id: "flagler-park",
    name: "Flagler Park",
    city: "Stuart",
    neighborhood: "Downtown",
    address: "121 SW Flagler Ave, Stuart, FL 34994",
    lat: 27.1985,
    lng: -80.2535,
  },
  {
    id: "midflorida",
    name: "MIDFLORIDA Event Center",
    city: "Port St. Lucie",
    address: "9221 SE Civic Center Place, Port St. Lucie, FL 34952",
    lat: 27.2758,
    lng: -80.3548,
  },
  {
    id: "tradition-square",
    name: "Tradition Square",
    city: "Port St. Lucie",
    neighborhood: "Tradition",
    address: "SW Meeting St, Port St. Lucie, FL 34987",
    lat: 27.269,
    lng: -80.388,
  },
  {
    id: "myrt-tharpe",
    name: "Myrt Tharpe Square",
    city: "Cocoa",
    neighborhood: "Cocoa Village",
    address: "12 Stone St, Cocoa, FL 32922",
    lat: 28.3215,
    lng: -80.737,
    url: "https://visitcocoavillage.com",
  },
  {
    id: "cocoa-village",
    name: "Historic Cocoa Village",
    city: "Cocoa",
    neighborhood: "Cocoa Village",
    address: "Brevard Ave, Cocoa, FL 32922",
    lat: 28.3208,
    lng: -80.7365,
    url: "https://visitcocoavillage.com",
  },
  {
    id: "playalinda",
    name: "Playalinda Brewing Company",
    city: "Titusville",
    address: "5220 S Washington Ave, Titusville, FL 32780",
    lat: 28.548,
    lng: -80.8065,
    url: "https://playalindabrewing.com",
  },
  {
    id: "intracoastal",
    name: "Intracoastal Brewing Company",
    city: "Eau Gallie",
    neighborhood: "EGAD",
    address: "652 W Eau Gallie Blvd, Melbourne, FL 32935",
    lat: 28.129,
    lng: -80.648,
    url: "https://intracoastalbrewingcompany.com",
  },
  {
    id: "green-gables",
    name: "Green Gables at Historic Riverview Village",
    city: "Melbourne",
    address: "1501 S Harbor City Blvd, Melbourne, FL 32901",
    lat: 28.0924,
    lng: -80.6272,
  },
  {
    id: "avenue-viera",
    name: "The Avenue Viera",
    city: "Viera",
    address: "2261 Town Center Ave, Melbourne, FL 32940",
    lat: 28.2452,
    lng: -80.7284,
  },
  {
    id: "viera-park",
    name: "Viera Regional Park",
    city: "Viera",
    address: "2300 Judge Fran Jamieson Way, Melbourne, FL 32940",
    lat: 28.244,
    lng: -80.741,
  },
  {
    id: "lakeside-viera",
    name: "Lakeside Social",
    city: "Viera",
    address: "1515 Trader Blvd, Melbourne, FL 32940",
    lat: 28.2465,
    lng: -80.7355,
  },
  {
    id: "slow-low-viera",
    name: "Slow & Low BBQ",
    city: "Viera",
    address: "7340 Lake Andrew Dr, Melbourne, FL 32940",
    lat: 28.2502,
    lng: -80.7288,
  },
  {
    id: "sams-island",
    name: "Sam's Island Music",
    city: "Merritt Island",
    address: "465 N Courtenay Pkwy, Merritt Island, FL 32953",
    lat: 28.3592,
    lng: -80.7074,
  },
  {
    id: "george-dragon",
    name: "George & Dragon English Tavern",
    city: "Cocoa",
    neighborhood: "Cocoa Village",
    address: "600 Brevard Ave, Cocoa, FL 32922",
    lat: 28.3218,
    lng: -80.7362,
  },
  {
    id: "nomads",
    name: "Nomads Canteen",
    city: "Melbourne",
    address: "1516 S Harbor City Blvd, Melbourne, FL 32901",
    lat: 28.0912,
    lng: -80.6278,
  },
  {
    id: "lyric",
    name: "Lyric Theatre",
    city: "Stuart",
    address: "59 SW Flagler Ave, Stuart, FL 34994",
    lat: 27.1978,
    lng: -80.2545,
    url: "https://www.lyrictheatre.com",
  },
  {
    id: "sunrise",
    name: "Sunrise Theatre",
    city: "Fort Pierce",
    address: "117 S 2nd St, Fort Pierce, FL 34950",
    lat: 27.4469,
    lng: -80.327,
    url: "https://www.sunrisetheatre.com",
  },
  {
    id: "veterans",
    name: "Brevard Veterans Memorial Center",
    city: "Merritt Island",
    address: "400 S Sykes Creek Pkwy, Merritt Island, FL 32952",
    lat: 28.357,
    lng: -80.679,
  },
  {
    id: "suntree-umc",
    name: "Suntree United Methodist Church",
    city: "Suntree",
    address: "7400 N Wickham Rd, Melbourne, FL 32940",
    lat: 28.22,
    lng: -80.68,
  },
  {
    id: "mihs",
    name: "Merritt Island High School Auditorium",
    city: "Merritt Island",
    address: "100 Mustang Way, Merritt Island, FL 32953",
    lat: 28.3594,
    lng: -80.7002,
  },
  {
    id: "first-church",
    name: "First Church Melbourne",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "110 E New Haven Ave, Melbourne, FL 32901",
    lat: 28.0836,
    lng: -80.6095,
  },
  {
    id: "dtmb",
    name: "Downtown Melbourne",
    city: "Melbourne",
    neighborhood: "Downtown",
    address: "E New Haven Ave, Melbourne, FL 32901",
    lat: 28.0836,
    lng: -80.607,
    url: "https://downtownmelbourne.com",
  },
  {
    id: "egad",
    name: "Eau Gallie Arts District",
    city: "Eau Gallie",
    neighborhood: "EGAD",
    address: "Pineapple Ave, Melbourne, FL 32935",
    lat: 28.132,
    lng: -80.631,
  },
  {
    id: "cape-downtown",
    name: "Downtown Cape Canaveral",
    city: "Cape Canaveral",
    address: "Atlantic Ave, Cape Canaveral, FL 32920",
    lat: 28.3882,
    lng: -80.6055,
  },
  {
    id: "palm-bay-market",
    name: "Palm Bay Farmers Market",
    city: "Palm Bay",
    address: "4220 Dixie Hwy NE, Palm Bay, FL 32905",
    lat: 28.0342,
    lng: -80.5884,
  },
  {
    id: "pelican-beach",
    name: "Pelican Beach Park",
    city: "Satellite Beach",
    address: "1525 Highway A1A, Satellite Beach, FL 32937",
    lat: 28.1765,
    lng: -80.5901,
  },
  {
    id: "walking-tree",
    name: "Walking Tree Brewery",
    city: "Vero Beach",
    address: "2123 14th Ave, Vero Beach, FL 32960",
    lat: 27.6386,
    lng: -80.3982,
    url: "https://walkingtreebrewery.com",
  },
  {
    id: "crowne-plaza",
    name: "Crowne Plaza Melbourne-Oceanfront",
    city: "Indialantic",
    address: "2605 N Highway A1A, Indialantic, FL 32903",
    lat: 28.1034,
    lng: -80.5702,
  },
  {
    id: "ebb-flow",
    name: "Ebb & Flow",
    city: "Cocoa Beach",
    address: "1 Minutemen Causeway, Cocoa Beach, FL 32931",
    lat: 28.3194,
    lng: -80.6072,
  },
  {
    id: "cocoa-civic",
    name: "City of Cocoa Civic Center",
    city: "Cocoa",
    address: "430 Delannoy Ave, Cocoa, FL 32922",
    lat: 28.3224,
    lng: -80.7352,
  },
  {
    id: "olive-branch",
    name: "Olive Branch GreenMarket",
    city: "Jensen Beach",
    address: "3750 NE Indian River Dr, Jensen Beach, FL 34957",
    lat: 27.2545,
    lng: -80.2268,
  },
];

export const VENUE_BY_ID: Record<string, Venue> = Object.fromEntries(
  VENUES.map((v) => [v.id, v]),
);
